pipeline:
  setup-db:
    image: postgres:16
    commands:
      - 'export DB_HOST="woodpecker-db-cluster.cluster-cbuqsk2gi5o4.ap-northeast-1.rds.amazonaws.com"'
      - 'export PGPASSWORD="password123"'
      - 'psql -h $DB_HOST -U postgres -d testdb -f src/sql/01_schema.sql'
      - 'psql -h $DB_HOST -U postgres -d testdb -f src/sql/02_seed.sql'
    when:
      - event: push
        branch: main
      - event: manual
      - event: deployment

  test:  # <--- ここ！ setup-db と縦のラインを揃える（重要）
    image: ovhcom/venom:latest
    commands:
      - 'export DB_HOST="woodpecker-db-cluster.cluster-cbuqsk2gi5o4.ap-northeast-1.rds.amazonaws.com"'
      - 'venom run src/tests/*.venom.yml --var "db_url=postgres://postgres:password123@$DB_HOST:5432/testdb" --var "api_url=https://8fb47xdz6i.execute-api.ap-northeast-1.amazonaws.com/dev"'
    when:
      - event: push
        branch: main
      - event: manual
      - event: deployment
